project_id = "cjkhwaetdfobwjqmxufx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = false

[auth]
enabled = true
port = 54324

[edge_functions]
enabled = true

[functions.nylas-webhook]
verify_jwt = false